apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-70"
spec:
  project: default
  source:
    repoURL: https://gitlab.com/zeropw/sre/sre-dev-eks.git
    targetRevision: main
    path: kubernetes/cluster-base
    helm:
      values: |-
        global:
          {{- toYaml .Values.global | nindent 10 }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
  syncPolicy:
    automated: {}
