apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-base
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-70"
spec:
  project: home
  source:
    repoURL: 'https://github.com/Berman510/pi-cluster.git'
    targetRevision: HEAD
    path: 'templates/deploy/applications/cluster-base/templates'
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
