apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: nginx-tls
  namespace: kube-system
spec:
  secretName: nginx-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - '*.bermanoc.net'
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - '*.bermanoc.net'
