---
storage_type: filesystem
storage_nfs_dir: "srv"
storage_nfs_share_name: nfsshare

master_node: 'rpi3'
certs_dir: '/Users/cberman/Repos/personal/pi-cluster/certs'
domain: 'bermanoc.net'
gateway: '10.17.84.1'
subnet_cidr: "10.17.84.0/24"
subnet_full_cidr: "10.0.0.0/8"

argo_cd_host: argocd.bermanoc.net
argo_cd_master: rpi3
argo_cd_master_ip: 10.17.84.23
argo_cd_host_name: rpi3
argo_cd_host_ip: 10.17.84.23
argo_cd_admin_password: $2y$10$SHW2FPelFcufdrA8OpclaOkLn3zMWhjdUJDj492idat4aARx3waxG

plex_node: rpi3

pihole_node: rpi3
pihole_node_ip: 10.17.84.23
pihole_passwd: admin

unbound_node: rpi3
unbound_node_ip: 10.17.84.23

openspeedtest_node: rpi3

iperf_node: rpi3

homeassistant_node: rpi3
homeassistant_node_ip: 10.17.84.23