---
storage_type: filesystem
storage_nfs_dir: "srv"
storage_nfs_share_name: nfsshare

master_node: 'rpi'
certs_dir: '/Users/cberman/Repos/personal/pi-cluster/certs'
domain: 'bermanoc.net'
gateway: '10.17.84.1'
subnet_cidr: "10.17.84.0/24"
subnet_full_cidr: "10.0.0.0/8"

argo_cd_host: argocd.bermanoc.net
argo_cd_master: rpi
argo_cd_master_ip: 10.17.84.2
argo_cd_host_name: nanopi02
argo_cd_host_ip: 10.17.84.22
argo_cd_admin_password: $2y$10$SHW2FPelFcufdrA8OpclaOkLn3zMWhjdUJDj492idat4aARx3waxG

plex_node: rpi

pihole_node: nanopi02
pihole_node_ip: 10.17.84.22
pihole_passwd: admin

unbound_node: nanopi01
unbound_node_ip: 10.17.84.21

openspeedtest_node: nanopi01

iperf_node: nanopi01

homeassistant_node: rpi
homeassistant_node_ip: 10.17.84.2