apiVersion: v1
kind: PersistentVolume
metadata:
  name: nvr-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}
