ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []

serviceAccount:
  create: true
  annotations: {}
  name: octoprint

replicaCount: 1

nodeSelector:
  kubernetes.io/hostname: nanopi02

image:
  repository: octoprint/octoprint
  tag: 1.8.7
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: 10.17.84.22

resources: {}
