---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: 1.11.0
    helm:
      releaseName: cert-manager
      values: |
        clusterResourceNamespace: "cert-manager"
        namespace: "cert-manager"
        installCRDs: true
        prometheus:
          enabled: true
        startupapicheck:
          timeout: 5m

  sources: []
  project: home
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
