---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homeassistant
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://k8s-at-home.com/charts/'
    targetRevision: 13.4.2
    chart: home-assistant
    helm:
      values: |
        image:
          tag: latest
        service:
          main:
            ports:
              http:
                port: 8123
            type: LoadBalancer
        ingress:
          #hostNetwork: true
          #dnsPolicy: ClusterFirstWithHostNet
          main:
            enabled: true
            annotations:
              #cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.org/websocket-services: home-assistant
            hosts:
              - host: 'homeassistant.{{ domain }}'
                paths:
                  - path: '/'
                    pathType: Prefix
        securityContext:
          privileged: true
        persistence:
          config:
            enabled: true
            type: hostPath
            hostPath: '/srv/nfsshare/homeassistant/config'
            mountPath: '/config'
          usb0:
            enabled: true
            type: hostPath
            hostPath: '/dev/ttyUSB0'
          usb1:
            enabled: true
            type: hostPath
            hostPath: '/dev/ttyUSB1'
          serial0:
            enabled: true
            type: hostPath
            hostPath: '/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_61600129-if00-port0'
          serial1:
            enabled: true
            type: hostPath
            hostPath: '/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_61600129-if01-port0'
        http:
          server_host: 0.0.0.0
          ip_ban_enabled: true
          login_attempts_threshold: 5
          use_x_forwarded_for: true
          trusted_proxies:
            - 10.42.1.220
            - 0.0.0.0/0
        nodeSelector:
          kubernetes.io/hostname: {{ homeassistant_node }}

  sources: []
  project: home
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
