---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homeassistant
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://k8s-at-home.com/charts/'
    #targetRevision: 13.4.2
    chart: home-assistant
    helm:
      values: |
        nodeSelector:
          kubernetes.io/hostname: {{ homeassistant_node }}
        image:
          tag: latest
          pullPolicy: IfNotPresent
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        service:
          main:
            ports:
              http:
                server_host: 0.0.0.0
                ip_ban_enabled: true
                login_attempts_threshold: 5
                use_x_forwarded_for: true
                trusted_proxies:
                  - 10.43.253.20
                  - 10.42.0.0/16
                  - 10.43.0.0/16
                  - 10.17.84.0/24
                  - 10.42.1.93
                port: 8123
            type: NodePort
        ingress:
          main:
            enabled: true
            #annotations:
            #  cert-manager.io/cluster-issuer: letsencrypt-prod
            #  nginx.org/websocket-services: home-assistant
            hosts:
              - host: 'homeassistant.{{ domain }}'
                paths:
                  - path: '/'
                    pathType: Prefix
            #tls:
            #  - secretName: letsencrypt-ca
            #    hosts:
            #      - homeassistant.{{ domain }}
        securityContext:
          privileged: true
        persistence:
          config:
            enabled: true
            type: hostPath
            hostPath: '/srv/nfsshare/homeassistant/config'
            mountPath: '/config'
          usb0:
            enabled: true
            type: hostPath
            hostPath: '/dev/ttyUSB0'
          usb1:
            enabled: true
            type: hostPath
            hostPath: '/dev/ttyUSB1'
          serial0:
            enabled: true
            type: hostPath
            hostPath: '/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_61600129-if00-port0'
          serial1:
            enabled: true
            type: hostPath
            hostPath: '/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_61600129-if01-port0'
        metrics:
          enabled: true
          serviceMonitor:
            interval: 1m
            scrapeTimeout: 30s
        mariadb:
          enabled: true
          architecture: standalone
          image:
            tag: 10.6.12
          auth:
            database: home-assistant
            username: home-assistant
            password: home-assistant-pass
            rootPassword: home-assistantrootpass
          primary:
            persistence:
              accessModes:
                - ReadWriteOnce
              enabled: false
              storageClass: nfs-client
        influxdb:
          enabled: true
          image:
            tag: 2.6.1
          architecture: standalone
          database: home_assistant
          authEnabled: false
          persistence:
            enabled: true
            storageClass: "nfs-client"
            size: 8Gi
        postgresql:
          enabled: true
          image:
            repository: bitnami/postgresql
            tag: 11.19.0
          postgresqlUsername: home-assistant
          postgresqlPassword: home-assistant-pass
          postgresqlDatabase: home-assistant
          persistence:
            primary:
              enabled: true
              storageClass: "nfs-client"
        addons:
          codeserver:
            enabled: true
            args:
              - --auth
              - none
              - --user-data-dir
              - /data/config/.vscode
            volumeMounts:
            - name: config
              mountPath: /data/config
  sources: []
  project: home
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
