---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homeassistant
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://helm.samipsolutions.fi/'
    targetRevision: 16.1.2
    chart: home-assistant
    helm:
      values: |
        nodeSelector:
          kubernetes.io/hostname: {{ homeassistant_node }}
        image:
          tag: latest
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        service:
          main:
            ports:
              http:
                server_host: 0.0.0.0
                ip_ban_enabled: true
                login_attempts_threshold: 5
                use_x_forwarded_for: true
                trusted_proxies:
                  - 10.42.0.79
                port: 8123
            type: NodePort
        ingress:
          main:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.org/websocket-services: home-assistant
            hosts:
              - host: 'homeassistant.{{ domain }}'
                paths:
                  - path: '/'
                    pathType: Prefix
            tls:
              - secretName: letsencrypt-ca
                hosts:
                  - homeassistant.{{ domain }}
        securityContext:
          privileged: true
        persistence:
          config:
            enabled: true
            type: hostPath
            hostPath: '/srv/nfsshare/homeassistant/config'
            mountPath: '/config'
          usb0:
            enabled: true
            type: hostPath
            hostPath: '/dev/ttyUSB0'
          usb1:
            enabled: true
            type: hostPath
            hostPath: '/dev/ttyUSB1'
          serial0:
            enabled: true
            type: hostPath
            hostPath: '/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_61600129-if00-port0'
          serial1:
            enabled: true
            type: hostPath
            hostPath: '/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_61600129-if01-port0'

  sources: []
  project: home
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
