---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-crd
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
      chart: 'https://%{KUBERNETES_API}%/static/charts/traefik-crd-20.3.1+up20.3.0.tgz'
  sources: []
  project: home
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true