---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
      chart: 'https://%{KUBERNETES_API}%/static/charts/traefik-20.3.1+up20.3.0.tgz'
      helm:
        values: |
          podAnnotations:
            prometheus.io/port: "8082"
            prometheus.io/scrape: "true"
          providers:
            kubernetesIngress:
              publishedService:
                enabled: true
          priorityClassName: "system-cluster-critical"
          image:
            name: "rancher/mirrored-library-traefik"
            tag: "2.9.4"
          tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Exists"
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"
          service:
            ipFamilyPolicy: "PreferDualStack"
  sources: []
  project: home
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true