---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homebridge
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  destination:
    namespace: homebridge
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://k8s-at-home.com/charts'
    targetRevision: 5.3.2
    chart: homebridge
    helm:
      values: |
        image:
          repository: homebridge/homebridge
          tag: latest
          pullPolicy: IfNotPresent
        ingress:
          main:
            enabled: true
            hosts:
              - host: "homebridge.{{ .Values.global.domain }}"
                paths:
                  path: /
                  pathType: Prefix
        persistence:
          config:
            enabled: true

  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
