---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homebridge
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  destination:
    namespace: homebridge
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'oci://tccr.io/truecharts/homebridge'
    targetRevision: 9.2.1
    helm:
      values: |
        env:
          TZ: "America/Los Angeles"
        ingress:
          enabled: true
          hosts:
            - host: homebridge.{{ .Values.global.domain }}
              paths:
                - path: /
                  pathType: ImplementationSpecific
        persistence:
          config:
            enabled: true
        podOptions:
          nodeSelector:
            kubernetes.io/arch: arm64
            kubernetes.io/hostname: nanopi03

  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
