---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homebridge
  namespace: argocd
spec:
  destination:
    namespace: homebridge
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/Berman510/pi-cluster'
    targetRevision: 0.1.2
    path: templates/charts/homebridge
    helm:
      values: |
        env:
          TZ: "America/Los Angeles"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "traefik"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          tls:
            - hosts:
              - frigate.{{ .Values.global.domain }}
              secretName: my-cert-tls
          hosts:
            - host: homebridge.{{ .Values.global.domain }}
              paths:
                - path: /
                  pathType: ImplementationSpecific
        persistence:
          config:
            enabled: true
        podOptions:
          nodeSelector:
            kubernetes.io/arch: arm64
            kubernetes.io/hostname: nanopi03

  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
