---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
    - group: "apps"
      kind: "StatefulSet"
  destination:
    namespace: loki
    server: 'https://kubernetes.default.svc'
  project: home
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "5.1.0"
    helm:
      releaseName: loki
      values: |
        gateway:
          enabled: true
          affinity: {}
          ingress:
            enabled: true
            hosts:
              - host: lokiingest.bermanoc.net
                paths:
                  - path: /
                    pathType: Prefix
        monitoring:       
          dashboards:
            enabled: true
          selfMonitoring:
            enabled: true
        minio:
          enabled: false
        loki:
          querier:
            tail_max_duration: 1h
          structuredConfig:
            ruler:
              alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.mimir-distributed-alertmanager-headless.mimir.svc.cluster.local/alertmanager
              enable_alertmanager_discovery: true 
              enable_api: true
          rulerConfig:
            alertmanager_url: http://_http-metrics._tcp.mimir-distributed-alertmanager-headless.mimir.svc.cluster.local/alertmanager
            enable_alertmanager_discovery: true
            enable_api: true
          auth_enabled: false
        serviceAccount:
          create: true
        
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
