apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "6.15.3"
    chart: promtail
    helm:
      values: |-
        serviceMonitor:
          enabled: true
        config:
          snippets:
            pipelineStages:
              - cri: {}
              - docker:
              - replace:
                  expression: '^\d{1,2}:\d{1,2}:\d{1,2} \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{9}Z (stdout|stderr) F'
                  replace:
              - match:
                  selector: '{app="eventrouter"}'
                  stages:
                  - json:
                      expressions:
                        namespace: event.metadata.namespace
                  - labels:
                      namespace: ""
            extraScrapeConfigs: |
              - job_name: journal
                journal:
                  path: /var/log/journal
                  max_age: 12h
                  labels:
                    job: systemd-journal
                relabel_configs:
                  - source_labels: ['__journal__systemd_unit']
                    target_label: 'unit'
                  - source_labels: ['__journal__hostname']
                    target_label: 'hostname'
          logLevel: info
          clients:
            - url: http://loki-gateway.loki.svc.cluster.local:80/loki/api/v1/push
        extraVolumes:
          - name: journal
            hostPath:
              path: /var/log/journal
        extraVolumeMounts:
          - name: journal
            mountPath: /var/log/journal
            readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: promtail
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
