---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  acme:
    email: "charlie.berman@gmail.com"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: aws-creds
    solvers:
    - selector:
        dnsZones:
          - "bermanoc.net"
      dns01:
        route53:
          region: us-west-2
          accessKeyIDSecretRef:
            name: prod-route53-credentials-secret
            key: access-key-id
          secretAccessKeySecretRef:
            name: prod-route53-credentials-secret
            key: secret-access-key