---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-cert
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  commonName: "*.bermanoc.net"
  dnsNames:
    - "*.bermanoc.net"
    - "bermanoc.net"
  secretName: my-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer