---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-cert
  namespace: cert-manager
spec:
  commonName: "*.bermanoc.net"
  dnsNames:
    - "*.bermanoc.net"
    - "bermanoc.net"
  secretName: my-cert-tls
  issuerRef:
    name: my-ca-issuer