---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-cert
  namespace: cert-manager
spec:
  commonName: "*.{{ domain }}"
  dnsNames:
    - "*.{{ domain }}"
    - "{{ domain }}"
  secretName: my-cert-tls
  issuerRef:
    name: my-ca-issuer
