apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  destination:
    namespace: kube-system
    name: in-cluster
  project: home
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 6.20.4
    helm:
      values: |
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::321447295215:role/externa-dns
        aws:
          credentials:
            secretKey: "aws-secret-access-key"
            accessKey: "aws-access-key-id"
        policy: sync
        domainFilters:
          - bermanoc.net
        logLevel: "info"
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws-secret-access-key
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
