apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  destination:
    namespace: kube-system
    name: in-cluster
  project: home
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 6.20.4
    helm:
      values: |
        serviceAccount:
          create: true
        aws:
          credentials:
            secretName: aws-credentials
            CredentialsChainVerboseErrors: true
        txtOwnerId: "external-dns-bermanoc-net"
        policy: sync
        domainFilters:
          - bermanoc.net
        logLevel: "info"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
