apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  destination:
    namespace: kube-system
    name: in-cluster
  project: home
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 6.20.4
    helm:
      values: |
        serviceAccount:
          create: true
        sources:
          - service
        aws:
          credentials:
            accessKeyIDSecretRef:
              name: "aws-credentials"
              key: "aws-access-key-id"
            secretAccessKeySecretRef:
              name: "aws-credentials"
              key: "aws-secret-access-key"
        policy: sync
        provider: aws
        registry: txt
        txtOwnerId: "extdns-internal-bermanoc-net"
        txtPrefix: "extdns-int-internal-bermanoc-net-"
        domainFilters:
          - bermanoc.net
        logLevel: "info"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
