---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  ignoreDifferences:
    - group: "apps"
      kind: "StatefulSet"
      name: loki-minio
      jsonPointers:
        - /spec/template/spec/persistentVolumeClaimRetentionPolicy
        - /spec/template/spec/volumeClaimTemplates/*
        - /spec/template/spec/volumeClaimTemplates/*/metadata/*
        - /spec/template/spec/volumeClaimTemplates/*/apiVersion/*
    - group: "apps"
      kind: "PodLogs"
      name: loki
      jsonPointers:
        - /spec/template/spec/relabelings/*
  project: home
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "5.36.3"
    chart: loki
    helm:
      skipCrds: true
      values: |
        commonConfig:
          replication_factor: 1
          path_prefix: /var/loki
        minio:
          enabled: true
          ingress:
            enabled: true
        #gateway:
        #  enabled: true
        #  ingress:
        #    enabled: true
        #    annotations:
        #      external-dns.alpha.kubernetes.io/hostname: lokiingest.bermanoc.net
        #    hosts:
        #      - host: lokiingest.bermanoc.net
        #        paths:
        #          - path: /
        #            pathType: Prefix
        loki:
          enabled: true
          auth_enabled: false
          #schema_config:
          #  configs:
          #  - from: 2020-10-24
          #    store: boltdb-shipper
          #    object_store: filesystem
          #    schema: v11
          #    index:
          #      prefix: loki_index_
          #      period: 24h
          #storage_config:
          #  boltdb_shipper:
          #    active_index_directory: /var/loki/index
          #    cache_location: /var/loki/cache
          #    cache_ttl: 24h       # Can be increased for longer caching
          #    shared_store: filesystem
          #  filesystem:
          #    directory: /var/loki/chunks
        monitoring:
          lokiCanary:
            enabled: true
            annotations:
              argocd.argoproj.io/hook: PreSync
          selfMonitoring:
            enabled: true
        test:
          enabled: false
        serviceAccount:
          create: true
        podSecurityContext:
          fsGroup: 10001
          limits:
            nofile:
              soft: 65536
              hard: 65536
        singleBinary:
          replicas: 1

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
