apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  ignoreDifferences:
    - group: "apps"
      kind: "StatefulSet"
      managedFieldsManagers:
        - loki-backend
      name: loki-backend
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
  project: home
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "5.36.3"
    chart: loki
    helm:
      skipCrds: true
      values: |-
        write:
          replicas: 3
          persistence:
            size: 30Gi
            storageClass: nfs-client
          nodeSelector:
            Function: monitoring
        read:
          replicas: 3
            size: 30Gi
          persistence:
            storageClass: nfs-client
        backend:
          replicas: 3
          persistence:
            size: 30Gi
            storageClass: nfs-client
        commonConfig:
          replication_factor: 3
          persistence:
            storageClass: nfs-client
        minio:
          enabled: true
          replicas: 3
          persistence:
            size: 30Gi
            storageClass: nfs-client
        loki:
          auth_enabled: false
          compactor:
            working_directory: /var/loki/compactor/retention
            shared_store: s3
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
          limits_config:
          retention_period: 72h
        monitoring:
          lokiCanary:
            enabled: false
          selfMonitoring:
            enabled: false
        test:
          enabled: false

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
