---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  ignoreDifferences:
    - group: "apps"
      kind: "StatefulSet"
      managedFieldsManagers:
        - loki-minio
      #name: minio
      #jsonPointers:
      #  - /spec/persistentVolumeClaimRetentionPolicy
      #  - /spec/volumeClaimTemplates
    - group: "apps"
      kind: "PodLogs"
      name: loki
      jsonPointers:
        - /spec/relabeling/*/action
  project: home
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "5.36.3"
    chart: loki
    helm:
      skipCrds: true
      values: |
        write:
          replicas: 3
          persistence::
            storageClass: nfs-client
        read:
          replicas: 3
          persistence::
            storageClass: nfs-client
        backend:
          replicas: 3
          persistence::
            storageClass: nfs-client
        commonConfig:
          replication_factor: 3
          persistence::
            storageClass: nfs-client
        minio:
          enabled: true
        gateway:
          enabled: true
          ingress:
            enabled: true
            annotations:
              external-dns.alpha.kubernetes.io/hostname: lokiingest.bermanoc.net
            hosts:
              - host: lokiingest.bermanoc.net
                paths:
                  - path: /
                    pathType: Prefix
        loki:
          enabled: true
          auth_enabled: false
        monitoring:
          enabled: true
          dashboards:
            enabled: true
          serviceMonitor:
            enabled: true
        serviceAccount:
          create: true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      #- ServerSideApply=true
