---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  ignoreDifferences:
    - group: "apps"
      kind: "StatefulSet"
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
  project: home
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "5.36.3"
    chart: loki
    helm:
      #skipCrds: true
      values: |
        minio:
          enabled: true
        backend:
          replicas: 1
        write:
          replicas: 1
        read:
          replicas: 1
        loki:
          storage:
            type: 'filesystem'
          singleBinary:
            replicas: 1
          auth_enabled: false
          compactor:
            working_directory: /var/loki/compactor/retention
            shared_store: s3
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
          limits_config:
          retention_period: 72h
        monitoring:
          lokiCanary:
            enabled: false
          selfMonitoring:
            enabled: false
        test:
          enabled: false

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
