---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  ignoreDifferences:
    - group: "apps"
      kind: "StatefulSet"
      name: loki-minio
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/volumeClaimTemplates/0/status
        - /spec/volumeClaimTemplates/0/metadata/creationTimestamp
        - /spec/volumeClaimTemplates/1/status
        - /spec/volumeClaimTemplates/1/metadata/creationTimestamp
  project: home
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "5.36.3"
    chart: loki
    helm:
      skipCrds: true
      values: |
        minio:
          enabled: true
        backend:
          replicas: 1
        write:
          replicas: 1
          persistence:
            storageClass: "local-path"
        read:
          replicas: 1
          persistence:
            storageClass: "local-path"
        gateway:
          enabled: true
          ingress:
            enabled: true
            annotations:
              external-dns.alpha.kubernetes.io/hostname: loki.bermanoc.net
            hosts:
              - host: lokiingest.bermanoc.net
                paths:
                  - path: /
                    pathType: Prefix
        loki:
          singleBinary:
            replicas: 1
          auth_enabled: false
          compactor:
            working_directory: /var/loki/compactor/retention
            shared_store: s3
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
          limits_config:
          retention_period: 72h
        monitoring:
          lokiCanary:
            enabled: true
            annotations:
              argocd.argoproj.io/hook: PreSync
          selfMonitoring:
            enabled: true
        test:
          enabled: false
        serviceAccount:
          create: true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
