---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  ignoreDifferences:
    - group: "apps"
      kind: "StatefulSet"
      name: loki-minio
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/volumeClaimTemplates/0/status
        - /spec/volumeClaimTemplates/0/metadata/creationTimestamp
        - /spec/volumeClaimTemplates/1/status
        - /spec/volumeClaimTemplates/1/metadata/creationTimestamp
  project: home
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "5.36.3"
    chart: loki
    helm:
      skipCrds: true
      values: |
        loki:
          commonConfig:
            replication_factor: 1
          enabled: true
          persistence:
            type: pvc
            enabled: true
          securityContext:
            runAsGroup: 10001
            runAsUser: 10001
          auth_enabled: false
          singleBinary:
            replicas: 1

        promtail:
          enabled: true

        fluent-bit:
          enabled: false

        grafana:
          enabled: false
          #namespaceOverride: grafana
          #sidecar:
          #  datasources:
          #    enabled: false
          #image:
          #  tag: 8.2.2
          #persistence:
          #  type: pvc
          #  enabled: true
          #  existingClaim: grafana
          #securityContext:
          #  runAsUser: 472
          #  runAsGroup: 472
          #initChownData:
          #  enabled: false

        prometheus:
          enabled: false
          #forceNamespace: prometheus
          #configmapReload:
          #  prometheus:
          #    enabled: false
          #  alertmanager:
          #    enabled: false
          #server:
          #  persistentVolume:
          #    enabled: true
          #    accessModes:
          #      - ReadWriteMany
          #  resources:
          #    limits:
          #      cpu: 800m
          #      memory: 1Gi
          #    requests:
          #      cpu: 500m
          #      memory: 512Mi
          #alertmanager:
          #  persistentVolume:
          #    enabled: true
          #    accessModes:
          #      - ReadWriteMany
          #  resources:
          #    limits:
          #      cpu: 100m
          #      memory: 100Mi
          #    requests:
          #      cpu: 50m
          #      memory: 50Mi
          #nodeExporter:
          #  enabled: true
          #  resources:
          #    limits:
          #      cpu: 200m
          #      memory: 50Mi
          #    requests:
          #      cpu: 100m
          #      memory: 30Mi

        filebeat:
          enabled: false

        logstash:
          enabled: false

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
