---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  ignoreDifferences:
    - group: "apps"
      kind: "StatefulSet"
      managedFieldsManagers:
        - loki-minio
    - group: "apps"
      kind: "StatefulSet"
      name: loki-minio
      jsonPointers:
        - /spec/volumeClaimTemplates
    - group: "apps"
      kind: "PodLogs"
      name: loki
      jsonPointers:
        - /spec/relabeling/*/action
  project: home
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "5.36.3"
    chart: loki
    helm:
      #skipCrds: true
      values: |
        write:
          replicas: 3
          persistence:
            storageClass: nfs-client
          affinity: |
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/monitoring
                    operator: In
                    values:
                    - "true"
        read:
          replicas: 3
          persistence:
            storageClass: nfs-client
          affinity: |
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/monitoring
                    operator: In
                    values:
                    - "true"
        backend:
          replicas: 3
          persistence:
            storageClass: nfs-client
          affinity: |
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/monitoring
                    operator: In
                    values:
                    - "true"
        commonConfig:
          replication_factor: 3
          persistence:
            storageClass: nfs-client
        minio:
          enabled: true
        loki:
          auth_enabled: false
          compactor:
            working_directory: /var/loki/compactor/retention
            shared_store: s3
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
          limits_config:
          retention_period: 72h
          affinity: |
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/monitoring
                    operator: In
                    values:
                    - "true"
        monitoring:
          lokiCanary:
            enabled: false
          selfMonitoring:
            enabled: false
        test:
          enabled: false

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
