---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  project: home
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: "3.11.0"
    helm:
      releaseName: metrics-server
      values: |
        metrics:
          enabled: true
        serviceMonitor:
          enabled: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true