---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omada
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'http://charts.charliehaley.dev'
    targetRevision: "0.9.0"
    chart: omada-exporter
    helm:
      values: |
        # Default values for omada_exporter.
        # This is a YAML-formatted file.
        # Declare variables to be passed into your templates.

        replicaCount: 1

        image:
          repository: ghcr.io/charlie-haley/omada_exporter
          pullPolicy: IfNotPresent

        omada:
            host: "https://10.17.84.3"
            username: "prometheus"
            password: "prometheus"
            site: "Home"
            insecure: true
            request_timeout: 15

        #Enable Prometheus ServiceMonitor
        serviceMonitor:
          enabled: true

        imagePullSecrets: []
        nameOverride: ""
        fullnameOverride: ""

        serviceAccount:
          create: true

        podAnnotations: {}

        podSecurityContext: {}
          # fsGroup: 2000

        securityContext: {}

        service:
          type: ClusterIP
          port: 9202

        ingress:
          enabled: false

        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi

        autoscaling:
          enabled: false
          minReplicas: 1
          maxReplicas: 1
          targetCPUUtilizationPercentage: 80
          # targetMemoryUtilizationPercentage: 80

        nodeSelector: {}

        tolerations: []

        affinity: {}
  sources: []
  project: home
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
