---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omada
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  destination:
    namespace: omada
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'http://charts.charliehaley.dev'
    targetRevision: "0.9.0"
    chart: omada-exporter
    helm:
      values: |
        replicaCount: 1
        image:
          repository: ghcr.io/charlie-haley/omada_exporter
        omada:
            host: "https://controller.bermanoc.net"
            username: "prometheus"
            password: "prometheus"
            site: "Home"
            insecure: false
            request_timeout: 15
        serviceMonitor:
          enabled: true
        serviceAccount:
          create: true
        service:
          type: ClusterIP
          port: 9202
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        autoscaling:
          enabled: false
        ingress:
          enabled: true
  sources: []
  project: home
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
