---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openspeedtest
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    traefik.http.middlewares.limit.buffering.maxRequestBodyBytes: '2500000000'
    traefik.http.routers.openspeedtest-https.middlewares: 'limit'
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  destination:
    namespace: openspeedtest
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://openspeedtest.github.io/Helm-chart'
    targetRevision: 0.1.2
    chart: openspeedtest
    helm:
      values: |
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: speedtest.bermanoc.net
              paths:
                - path: /
                  pathType: ImplementationSpecific
        nodeSelector:
          kubernetes.io/hostname: nanopi01
  sources: []
  project: home
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
