---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: plex
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://k8s-at-home.com/charts'
    targetRevision: 6.4.3
    chart: plex
    helm:
      values: |
        env:
          TZ: PST
        service:
          main:
            type: LoadBalancer
            primary: true
            ports:
              http:
                port: 32400
          dnla-tcp:
            enabled: true
            type: NodePort
            ports:
              dnla-tcp:
                enabled: true
                port: 32469
                protocol: TCP
                targetPort: 32469
            externalTrafficPolicy: Local
          dnla-udp:
            enabled: true
            type: NodePort
            ports:
              dnla-udp:
                enabled: true
                port: 1900
                protocol: TCP
                targetPort: 1900
            externalTrafficPolicy: Local
        ingress:
          main:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: plex.{{ domain }}
                paths:
                  - path: /
                    pathType: ImplementationSpecific
        nodeSelector:
          kubernetes.io/hostname: {{ plex_node }}
        persistence:
          config:
            enabled: true
            mountPath: /config
            storageClass: nfs-client
          transcode:
            enabled: false
            mountPath: /transcode
            storageClass: nfs-client

  sources: []
  project: home
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
