---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tempo
  project: home
  source:
    chart: tempo-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "1.7.0"
    helm:
      releaseName: tempo-distributed
      values: |
        serviceAccount:
          create: true
        ingester:
          replicas: 3
          autoscaling:
            enabled: false
            minReplicas: 1
            maxReplicas: 4
            targetCPUUtilizationPercentage: 60
            targetMemoryUtilizationPercentage: 80
          topologySpreadConstraints: {}  
          tolerations:
            - key: "dedicated"
              operator: "Equal"
              value: "ObservabilityGroup"
              effect: "NoSchedule"
          nodeSelector:
            nodeGroup: ObservabilityGroup
          persistence:
            enabled: true
            storageClass: "encrypted-gp3"
            size: 50Gi
        distributor:
          replicas: 1
          autoscaling:
            enabled: false
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 60
            targetMemoryUtilizationPercentage: 80
        compactor:
          replicas: 1
          config:
            compaction:
              # -- Duration to keep blocks
              block_retention: 48h
              # Duration to keep blocks that have been compacted elsewhere
              compacted_block_retention: 1h
              # -- Blocks in this time window will be compacted together
              compaction_window: 1h
              # -- Amount of data to buffer from input blocks
              v2_in_buffer_bytes: 5242880
              # -- Flush data to backend when buffer is this large
              v2_out_buffer_bytes: 20971520
              # -- Maximum number of traces in a compacted block. WARNING: Deprecated. Use max_block_bytes instead.
              max_compaction_objects: 6000000
              # -- Maximum size of a compacted block in bytes
              max_block_bytes: 107374182400
              # -- Number of tenants to process in parallel during retention
              retention_concurrency: 10
              # -- Number of traces to buffer in memory during compaction
              v2_prefetch_traces_count: 1000
              # -- The maximum amount of time to spend compacting a single tenant before moving to the next
              max_time_per_tenant: 5m
              # -- The time between compaction cycles
              compaction_cycle: 30s                         
        querier:
          replicas: 1
          autoscaling:
            enabled: false
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 60
            targetMemoryUtilizationPercentage: 80
        metaMonitoring:
          serviceMonitor:
            enabled: true
        gateway:
          enabled: true
          replicas: 1
          autoscaling:
            enabled: false
            minReplicas: 1
            maxReplicas: 4
            targetCPUUtilizationPercentage: 60
            targetMemoryUtilizationPercentage: 80
          verboseLogging: true
          ingress:
            enabled: true
            annotation:
              kubernetes.io/ingress.class: "traefik"
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - host: tempo.bermanoc.net
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - hosts:
                - tempo.bermanoc.net
                secretName: my-cert-tls
          multitenancyEnabled: false
          
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
