---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-deploy
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    server: 'https://kubernetes.default.svc'
  project: home
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: "25.0.0"
    helm:
      releaseName: traefik
      values: |
        deployment:
          enabled: true
          kind: Deployment
          replicas: 1
        autoscaling:
          enabled: true
          minReplicas: 1
          maxReplicas: 1
          metrics:
          - type: Resource
            resource:
              name: memory
              target:
                type: Utilization
                averageUtilization: 60
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 60
        updateStrategy:
          rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1
        logs:
          general:
            level: WARN
          access:
            enabled: true
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
        service:
          enabled: true
          type: LoadBalancer
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          spec:
            externalTrafficPolicy: Cluster
        ports:
          traefik:
            port: 9000
            expose: false
            exposedPort: 9000
            protocol: TCP
          web:
            port: 8000
            expose: true
            exposedPort: 80
            protocol: TCP
            redirectTo: websecure
          websecure:
            port: 8443
            expose: true
            exposedPort: 443
            protocol: TCP
            http3:
              enabled: false
            tls:
              enabled: false
              options: ""
              certResolver: ""
              domains: []
            middlewares: []
        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
          limits:
            cpu: "400m"
            memory: "1Gi"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
