---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-deploy
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    server: 'https://kubernetes.default.svc'
  project: home
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: "25.0.0"
    helm:
      releaseName: traefik
      values: |
        deployment:
          enabled: true
          kind: Deployment
        logs:
          general:
            level: WARN
          access:
            enabled: true
        providers:
          kubernetesIngress:
            publishedService:
              enabled: true
        service:
          enabled: true
          type: LoadBalancer
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
          limits:
            cpu: "400m"
            memory: "1Gi"
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
