---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  acme:
    email: "{{ .Values.global.cert_email }}"
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - "{{ .Values.global.domain }}"
      dns01:
        route53:
          region: us-west-2
          accessKeyIDSecretRef:
            name: aws-creds
            key: aws-access-key-id
          secretAccessKeySecretRef:
            name: aws-creds
            key: aws-secret-access-key
