apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homebridge.fullname" . }}
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "homebridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "homebridge.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8581
              name: http
          env:
            - name: TZ
              value: "{{ .Values.env.TZ }}"
          volumeMounts:
            - name: config
              mountPath: /homebridge
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "homebridge.fullname" . }}-config
