{{- $serviceAccount := .Values.serviceAccount | default dict }}
{{- $create := $serviceAccount.create | default true }}
{{- if $create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccount.name | default (include "homebridge.fullname" .) }}
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
{{- end }}
