---
- name: Ensure NFS share directory exists.
  ansible.builtin.file:
    dest: "/{{ storage_nfs_dir }}/{{ storage_nfs_share_name }}"
    owner: root
    group: pi
    state: directory
    mode: 0777

- name: Ensure NFS is installed.
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present

- name: Configure NFS exports for nodes and control_plane groups
  ansible.builtin.blockinfile:
    path: /etc/exports
    block: |
      /{{ storage_nfs_dir }}/{{ storage_nfs_share_name }} {% for host in groups['nodes'] + groups['control_plane'] %}{{ hostvars[host]['ansible_host'] }}(rw,sync,no_root_squash) {% endfor %}
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
  register: nfs_exports_configured

- name: Reload NFS exports
  ansible.builtin.command: exportfs -ra
  become: true
  when: nfs_exports_configured.changed

- name: Ensure NFS is started and enabled at boot.
  ansible.builtin.service:
    name: nfs-server
    state: started
    enabled: true
