apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "6.15.3"
    chart: promtail
    helm:
      values: |-
        serviceMonitor:
          enabled: true
        config:
          logLevel: info
          clients:
            - url: http://loki-gateway.loki.svc.cluster.local:80/loki/api/v1/push
        extraVolumes:
          - name: journal
            hostPath:
              path: /var/log/journal
        extraVolumeMounts:
          - name: journal
            mountPath: /var/log/journal
            readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: promtail
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
