---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: 1.13.3
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        extraArgs:
          - --dns01-recursive-nameservers-only
          - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
        prometheus:
          enabled: true
          servicemonitor:
            enabled: true
        startupapicheck:
          timeout: 5m

  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true