apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-55"
spec:
  ignoreDifferences:
    - group: "apps"
      kind: "StatefulSet"
      managedFieldsManagers:
        - loki-minio
    - group: "apps"
      kind: "StatefulSet"
      name: loki-minio
      jsonPointers:
        - /spec/volumeClaimTemplates
    - group: "apps"
      kind: "PodLogs"
      name: loki
      jsonPointers:
        - /spec/relabeling/*/action
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "5.36.3"
    chart: loki
    helm:
      skipCrds: true
      values: |-
        write:
          replicas: 3
          persistence:
            storageClass: nfs-client
        read:
          replicas: 3
          persistence:
            storageClass: nfs-client
        backend:
          replicas: 3
          persistence:
            storageClass: nfs-client
        commonConfig:
          replication_factor: 3
          persistence:
            storageClass: nfs-client
        minio:
          enabled: true
          replicas: 3
          persistence:
            storageClass: nfs-client
        loki:
          auth_enabled: false
          compactor:
            working_directory: /var/loki/compactor/retention
            shared_store: s3
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
          limits_config:
          retention_period: 72h
        monitoring:
          lokiCanary:
            enabled: false
          selfMonitoring:
            enabled: false
        test:
          enabled: false
        ingress:
          enabled: true
          hosts:
            - loki.{{ .Values.global.domain }}
          annotations:
            kubernetes.io/ingress.class: "traefik"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            traefik.ingress.kubernetes.io/router.tls: "true"
          tls:
            - hosts:
              - loki.{{ .Values.global.domain }}
              secretName: my-cert-tls

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: loki

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
