---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-mimir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mimir
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: mimir-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "5.2.0"
    helm:
      releaseName: mimir-distributed
      values: |
        serviceAccount:
          create: true
        distributor:
          extraArgs:
            distributor.ingestion-rate-limit: "1000000"
            distributor.ingestion-burst-size: "10000000"
            validation.max-label-names-per-series: "38"
        ingester:
          extraVolumes:
            - name: tsdb
              emptyDir: {}
          extraVolumeMounts:
            - name: tsdb
              mountPath: /tsdb
          extraArgs:
            ingester.max-global-series-per-user: "0"
            ingester.max-global-series-per-metric: "0"
          persistentVolume:
            enabled: true
            storageClass: nfs-client
            size: 50Gi
          zoneAwareReplication:
            enabled: false
        querier:
          extraArgs:
            querier.query-store-after: "0s"
            querier.shuffle-sharding-ingesters-enabled: "false"
        store_gateway:
          extraVolumes:
            - name: tsdb
              emptyDir: {}
          extraVolumeMounts:
            - name: tsdb
              mountPath: /tsdb-sync
          extraArgs:
            blocks-storage.bucket-store.sync-interval: "5m"
            blocks-storage.bucket-store.ignore-blocks-within: "0s"
            blocks-storage.bucket-store.metadata-cache.bucket-index-content-ttl: "1m"
            blocks-storage.bucket-store.metadata-cache.tenants-list-ttl: "1m"
            blocks-storage.bucket-store.metadata-cache.tenant-blocks-list-ttl: "1m"
            blocks-storage.bucket-store.metadata-cache.metafile-doesnt-exist-ttl: "1m"
          persistentVolume:
            enabled: true
            size: 10Gi
            storageClass: nfs-client
          zoneAwareReplication:
            enabled: false
        compactor:
          extraArgs:
            compactor.blocks-retention-period: "90d"
            compactor.cleanup-interval: "5m"
          persistentVolume:
            enabled: true
            size: 10Gi
            storageClass: nfs-client
        minio:
          enabled: false
        nginx:
          enabled: false
        mimir:
          config: |
            activity_tracker:
              filepath: /data/metrics-activity.log
            alertmanager:
              enable_api: true
              data_dir: /data
              enable_api: true
              external_url: /alertmanager
            compactor:
              data_dir: /data
            frontend:
              align_queries_with_step: true
              log_queries_longer_than: 10s
              parallelize_shardable_queries: true
              scheduler_address: mimir-distributed-query-scheduler-headless.mimir.svc:9095
            frontend_worker:
              scheduler_address: mimir-distributed-query-scheduler-headless.mimir.svc:9095
            ingester:
              ring:
                final_sleep: 0s
                num_tokens: 512
                tokens_file_path: /data/tokens
                unregister_on_shutdown: true
                zone_awareness_enabled: false
            ingester_client:
              grpc_client_config:
                max_recv_msg_size: 104857600
                max_send_msg_size: 104857600
            limits:
              max_query_parallelism: 224
              max_global_series_per_user: 100000000
              ruler_max_rules_per_rule_group: 100
              ruler_max_rule_groups_per_tenant: 200
              max_global_series_per_metric: 100000
            memberlist:
              abort_if_cluster_join_fails: false
              compression_enabled: false
              join_members:
              - dns+mimir-distributed-gossip-ring.mimir.svc.cluster.local:7946
            querier:
              max_concurrent: 16
            query_scheduler:
              max_outstanding_requests_per_tenant: 1600
            ruler:
              alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.mimir-distributed-alertmanager-headless.mimir.svc.cluster.local/alertmanager
              enable_api: true
              rule_path: /data
            runtime_config:
              file: /var/mimir/runtime.yaml
            server:
              grpc_server_max_concurrent_streams: 1000
              grpc_server_max_connection_age: 2m
              grpc_server_max_connection_age_grace: 5m
              grpc_server_max_connection_idle: 1m
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true