---
- name: Configure Argo-CD.
  hosts: control_plane
  gather_facts: false
  become: true

  vars_files:
    - ../../config.yml

  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  tasks:
    - name: Create Argo-CD namespace.
      k8s:
        name: argocd
        api_version: v1
        kind: Namespace
        state: present

    - name: Add Argo-CD chart repo.
      kubernetes.core.helm_repository:
        name: argo
        repo_url: "https://argoproj.github.io/argo-helm"

    - name: Deploy Argo-CD Helm chart.
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        state: present
        values:
          params:
            server.insecure: true
          alertmanager:
            enabled: false
          controller:
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
          configs:
            repositories:
              pi-cluster:
                url: https://github.com/Berman510/pi-cluster.git
            secret:
              argocdServerAdminPassword: "{{ argo_cd_admin_password }}"
          repoServer:
            replicas: 1
            autoscaling:
              enabled: false
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
          server:
            extraArgs:
            - --insecure
            service:
              externalIPs:
                - "{{ argo_cd_host_ip }}"
              loadBalancerIP: "{{ argo_cd_host_ip }}"
              type: "NodePort"
            metrics:
              enabled: true
              serviceMonitor:
                enabled: true
            ingress:
              enabled: true
              hosts:
                - "argocd.{{ domain }}"
              paths:
                - /
              pathType: Prefix
              https: false
