---
- name: Deploy Argo-CD Apps
  hosts: control_plane
  gather_facts: false
  become: true

  vars_files:
    - ../../config.yml

  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  tasks:
    - name: Clone pi-cluster repository
      git:
        repo: 'https://github.com/Berman510/pi-cluster.git'
        dest: '/root/pi-cluster'
        version: 'master' # or the branch/tag you want to use

    - name: Deploy entrypoint chart to Argo-CD
      kubernetes.core.helm:
        release_name: entrypoint
        chart_ref: '/root/pi-cluster/templates/deploy/entrypoint'
        namespace: argocd
        state: present
