---
- name: Configure Prometheus Grafana monitoring stack.
  hosts: control_plane
  gather_facts: false
  become: true

  vars_files:
    - ../../config.yml

  environment:
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  tasks:
    - name: Add prometheus-community chart repo.
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Deploy Prometheus + Grafana Helm chart.
      kubernetes.core.helm:
        name: cluster-monitoring
        chart_ref: prometheus-community/kube-prometheus-stack
        chart_version: 48.4.0
        release_namespace: monitoring
        state: present
        values: 
          prometheus:
            ingress:
              enabled: true
              hosts:
                - prometheus.{{ domain }}
              path: /
              pathType: Prefix
            prometheusSpec:
              additionalScrapeConfigs:
                - job_name: 'home-assistant'
                  metrics_path: '/api/prometheus'
                  scrape_interval: 60s
                  bearer_token: "{{ prometheus_bearer_token }}"
                  scheme: http
                  static_configs:
                    - targets: 
                      - '10.17.84.2:8123'
                - job_name: 'omada-exporter'
                  metrics_path: '/metrics'
                  scrape_interval: 60s
                  scheme: http
                  static_configs:
                    - targets: 
                      - 'omada-omada-exporter:9202'
          alertmanager:
            enabled: false
          grafana:
            ingress:
              enabled: true
              hosts:
                - grafana.{{ domain }}
              path: /
          sidecar:
            dashboards:
              enabled: true
