---
apiVersion: v1
kind: Secret
metadata:
  name: pi-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  project: home
  url: https://github.com/Berman510/pi-cluster.git